# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canta_mais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='quemSugeriu',
            field=models.CharField(default='eu', max_length=100),
        ),
    ]
